version: '3.8'
services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - venet

  # Service for the auth api
  ms-auth:
    container_name: ms-auth
    build:
      context: ./ms-vecinet-auth-api
      dockerfile: Dockerfile
    env_file: ./vecinet-envs/ms-vecinet-auth-api/local/.env
    ports:
      - "8092:8092"
    volumes:
      - gradle-cache:/home/gradle/.gradle
    networks:
      - venet

  # Service for the worker
  worker:
    container_name: ms-worker
    depends_on:
      - rabbitmq
    build:
      context: ./ms-vecinet-create-post-worker
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file: ./vecinet-envs/ms-vecinet-create-post-worker/local/compose.env
    volumes:
      - gradle-cache:/home/gradle/.gradle
    networks:
      - venet

  # Service for the worker
  ms-vecinet-post-api:
    container_name: ms-post
    depends_on:
      - rabbitmq
    build:
      context: ./ms-vecinet-post-api
      dockerfile: Dockerfile
    ports:
      - "8093:8093"
    env_file: ./vecinet-envs/ms-vecinet-post-api/local/compose.env
    volumes:
      - gradle-cache:/home/gradle/.gradle
    networks:
      - venet

networks:
  venet:
    driver: bridge
    external: true
volumes:
  gradle-cache:
  rabbitmq_data:
  rabbitmq_log: